export const sample2PlayerMatch = {
  matchId: "SR12345",
  gameMode: "Attrition",
  queueId: "Queue1",
  ranked: true,
  maps: [
    {
      mapName: "Nerve Center Small",
      gameMode: "Attrition",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team1 Wins",
      finalScores: {
        team1: 22,
        team2: 16,
      },
    },
    {
      mapName: "Pinnacle",
      gameMode: "Attrition",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team2 Wins",
      finalScores: {
        team1: 18,
        team2: 16,
      },
    },
    {
      mapName: "Lobby",
      gameMode: "Extraction",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team1 Wins",
      finalScores: {
        team1: 18,
        team2: 16,
      },
    },
  ],
  players: [
    {
      playerId: "Player1",
      discordId: "player1",
      stats: [
        {
          teamSize: 2,
          elo: 1000,
          kills: 10,
          deaths: 1,
          resurrects: 1,
          avgMoney: 123,
        },
      ],
    },
    {
      playerId: "Player2",
      discordId: "player2",
      stats: [
        {
          teamSize: 2,
          elo: 1114,
          kills: 13,
          deaths: 13,
          resurrects: 5,
          avgMoney: 33,
        },
      ],
    },
  ],
  teamSize: 2,
  winner: "Team1",
};

export const sample4PlayerMatch = {
  matchId: "SR123",
  gameMode: "Attrition",
  queueId: "Queue1",
  ranked: true,
  maps: [
    {
      mapName: "Nerve Center Small",
      gameMode: "Attrition",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team1 Wins",
      finalScores: {
        team1: 18,
        team2: 16,
      },
    },
    {
      mapName: "Pinnacle",
      gameMode: "Attrition",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team2 Wins",
      finalScores: {
        team1: 18,
        team2: 16,
      },
    },
    {
      mapName: "Lobby",
      gameMode: "Extraction",
      scoredBy: {
        team1: "Player1",
        team2: "Player3",
      },
      players: [
        {
          playerId: "Player1",
          team: "Team1",
          kills: 10,
          deaths: 3,
          resurrects: 2,
          totalMoneyEarned: 500,
        },
        {
          playerId: "Player2",
          team: "Team1",
          kills: 8,
          deaths: 5,
          resurrects: 1,
          totalMoneyEarned: 450,
        },
        {
          playerId: "Player3",
          team: "Team2",
          kills: 7,
          deaths: 4,
          resurrects: 3,
          totalMoneyEarned: 480,
        },
        {
          playerId: "Player4",
          team: "Team2",
          kills: 9,
          deaths: 6,
          resurrects: 0,
          totalMoneyEarned: 420,
        },
      ],
      result: "Team1 Wins",
      finalScores: {
        team1: 18,
        team2: 16,
      },
    },
  ],
  players: [
    {
      playerId: "Player1",
      discordId: "player1",
      stats: [
        {
          teamSize: 2,
          elo: 1000,
          kills: 10,
          deaths: 1,
          resurrects: 1,
          avgMoney: 123,
        },
      ],
    },
    {
      playerId: "Player2",
      discordId: "player2",
      stats: [
        {
          teamSize: 2,
          elo: 1114,
          kills: 13,
          deaths: 13,
          resurrects: 5,
          avgMoney: 33,
        },
      ],
    },
  ],
  teamSize: 2,
  winner: "Team1",
};
